In [6]:
import numpy as np

In [7]:
a = [10, 11, 12, 13, 14, 15]

In [8]:
n_a = np.array(a)

In [9]:
n_a

array([10, 11, 12, 13, 14, 15])

In [10]:
n_a[0]

10

In [11]:
n_a[1]

11

In [12]:
last_index = len(n_a) - 1

In [13]:
n_a[last_index]

15

In [14]:
n_a[-1]

15

In [15]:
n_a[-2]

14

In [16]:
n_a[0:3]

array([10, 11, 12])

In [17]:
n_a[0:-1:]

array([10, 11, 12, 13, 14])

In [18]:
n_a[0:-1:2]

array([10, 12, 14])

In [19]:
n_a[:3]

array([10, 11, 12])

In [20]:
n_a[3:6]

array([13, 14, 15])

In [21]:
n_a[2:4]

array([12, 13])

In [22]:
n_a[1:5]

array([11, 12, 13, 14])

In [23]:
n_a[::2]

array([10, 12, 14])

In [24]:
n_a[1::2]

array([11, 13, 15])

In [25]:
n_b = np.array([100, 101, 102, 103, 104, 105])

In [26]:
n_c = np.concatenate([n_a, n_b])

In [27]:
n_c

array([ 10,  11,  12,  13,  14,  15, 100, 101, 102, 103, 104, 105])

In [28]:
np.sum(n_a)

75

In [29]:
np.sum(n_c)

690

In [30]:
np.max(n_c)

105

In [31]:
np.min(n_c)

10

In [32]:
np.mean(n_c)

57.5

In [33]:
n_random = np.random.random(10)

In [34]:
n_random

array([0.58225019, 0.73025371, 0.44310199, 0.89163236, 0.21287356,
       0.72529039, 0.98504171, 0.10968345, 0.06324363, 0.22740918])

In [35]:
np.max(n_random)

0.985041710222267

In [36]:
np.min(n_random)

0.06324362821456653

In [37]:
np.sort(n_random)

array([0.06324363, 0.10968345, 0.21287356, 0.22740918, 0.44310199,
       0.58225019, 0.72529039, 0.73025371, 0.89163236, 0.98504171])

In [38]:
np.argsort(n_random)

array([8, 7, 4, 9, 2, 0, 5, 1, 3, 6])

In [39]:
np.sort(n_random[::-1])

array([0.06324363, 0.10968345, 0.21287356, 0.22740918, 0.44310199,
       0.58225019, 0.72529039, 0.73025371, 0.89163236, 0.98504171])

In [40]:
np.sort(n_random)[::-1]

array([0.98504171, 0.89163236, 0.73025371, 0.72529039, 0.58225019,
       0.44310199, 0.22740918, 0.21287356, 0.10968345, 0.06324363])